name: lint

on:
  push:
    branches:
      - develop
      - main
      - master
      - deploy
  pull_request:
    branches:
      - develop
      - main
      - master
      - deploy

permissions:
  contents: write

jobs:
  lint:
    runs-on: ubuntu-latest
    environment: Testing
    outputs:
      lint-status: ${{ job.status }}
    steps:
      - uses: actions/checkout@v4

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.4'

      - name: Add Flux Credentials
        run: composer config http-basic.composer.fluxui.dev "${{ secrets.FLUX_USERNAME }}" "${{ secrets.FLUX_LICENSE_KEY }}"

      - name: Install Dependencies
        run: |
          composer install -q --no-ansi --no-interaction --no-scripts --no-progress --prefer-dist
          npm install

      - name: Run Pint (Code Style Check)
        run: vendor/bin/pint --test

      - name: Run Pint (Fix Code Style)
        if: failure()
        run: vendor/bin/pint

      # - name: Commit Changes
      #   uses: stefanzweifel/git-auto-commit-action@v5
      #   with:
      #     commit_message: fix code style
      #     commit_options: '--no-verify'
      #     file_pattern: |
      #       **/*
      #       !.github/workflows/*
